apiVersion: v1
kind: Pod
metadata:
  name: train-pod
spec:
  restartPolicy: Never
  containers:
  - name: train
    image: docker.io/chengziyun/hw5-training:v3
    imagePullPolicy: Always
    ports:
    - containerPort: 5000
    volumeMounts:
      - name: app-pv
        mountPath: /home/app
  volumes:
    - name: app-pv
      persistentVolumeClaim:
        claimName: model-holder
