apiVersion: v1
kind: Pod
metadata:
  name: train-pod
spec:
  containers:
  - name: train
    image: gcr.io/core-verbena-328218/mnist_train:2.0
    ports:
    - containerPort: 5000
    resources:
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-tesla-t4
